name = "line-site-backend"
main = "main.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date  = "2025-08-20"

# Static assets
[assets]
directory = "./assets"
binding = "ASSETS"

# D1 ローカル開発用設定
[[d1_databases]]
binding = "LINE_D1"
database_name = "line_site_db"
database_id = "dev"  # 開発環境用の識別子


 
