name = "line-site-backend"
main = "main.ts"
compatibility_date = "2024-12-20"
compatibility_flags = ["no_handle_cross_request_promise_resolution", "nodejs_compat"]

# D1 ローカル開発用設定
[[d1_databases]]
binding = "LINE_D1"
database_name = "line_site_db"
database_id = "dev"  # 開発環境用の識別子


 
